### ISSUE TITLE
change gender of connected node?

### ISSUE THREAD

**Issue by mkozakov** [mkozakov/PGraph#14]
does connection disappear? can gender be changed?

**Comment by marta-** [comment]
Remember the user should be informed, but not (too) constrained. In this case, you could probably display a warning about the partner incompatibility and allow the user to choose whether to:
- cancel the change
- make the change anyway, even though it generates conflicts, in which case the connections are clearly displayed as erroneous (e.g. red)
- make the change and break all connections (to decide what happens to the children; they should be assigned to one of the parents, probably the one that hasn't been changed).
